config/routes.rb
Refout::Application.routes.draw do
  resources :tips do
    member do
      put "addupvote", to: "tips#addupvote"
    end
  end

  resources :groups

  resources :offices

  resources :banks do
    get :offices, :on => :member
    get :groups, :on => :member
    get :schools, :on => :member
  end

  resources :recruiters

  resources :headhunters

  scope '/resources' do
    resources :tips
    get "what-to-read" => "pages#resources/what-to-read"
  end

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "resources" => "pages#resources"
  get "legal" => "pages#legal"
  

end

app/models/headhunter.rb
class Headhunter < ActiveRecord::Base
	has_many :recruiters

	scope :isMega, -> {where(:mega => true)}
	scope :Undergrad, -> {where(:CompanyUndergrad => true)}
	scope :PreMBA, -> {where(:CompanyPreMBA => true)}
	scope :PostMBA, -> {where(:CompanyPostMBA => true)}
	scope :Executive, -> {where(:CompanyExecutive => true)}
	scope :hasJobs, -> {where("\"CompanyJobs\" != ?", "None")}

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/headhunters_controller.rb
class HeadhuntersController < ApplicationController
  before_action :set_headhunter, only: [:show, :edit, :update, :destroy]
  # before_action :authenticate_user!, only: [:new]
  before_filter :verify_is_admin, only: [:new, :edit, :update, :destroy]
  has_scope :isMega, :type => :boolean
  has_scope :Undergrad, :type => :boolean
  has_scope :PreMBA, :type => :boolean
  has_scope :PostMBA, :type => :boolean
  has_scope :Executive, :type => :boolean
  has_scope :hasJobs, :type => :boolean


  def index
    # @headhunters_updated = Headhunter.all.order("updated_at DESC").paginate(:page => params[:page], :per_page => 12)
    # @headhunters_alphabetical = Headhunter.all.order(:CompanyName).paginate(:page => params[:page], :per_page => 12)
    # @headhunters_added = Headhunter.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 12)
    
    @headhunters = apply_scopes(Headhunter.all.order(:CompanyName).paginate(:page => params[:page], :per_page => 24))

  end

  def show
    @headhunter = Headhunter.find(params[:id])
    @recruiters = @headhunter.recruiters.order(:name).paginate(:page => params[:page], :per_page => 20)
  end

  def new
    @headhunter = Headhunter.new
  end

  def edit
  end

  def create
    @headhunter = Headhunter.new(headhunter_params)

    if @headhunter.save
      redirect_to @headhunter, notice: 'Headhunter was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @headhunter.update(headhunter_params)
      redirect_to @headhunter, notice: 'Headhunter was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @headhunter.destroy
    redirect_to headhunters_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_headhunter
      @headhunter = Headhunter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def headhunter_params
      params.require(:headhunter).permit(:CompanyName, :CompanyDescription, :CompanyEmail, :CompanyWebsite, :CompanyLinkedin, :CompanyFacebook, :CompanyTwitter, :image, :CompanyUndergrad, :CompanyPreMBA, :CompanyPostMBA, :CompanyExecutive, :mega, :CompanyCandidateArea, :CompanyJobs, :street1, :city1, :phone1, :street2, :city2, :phone2, :street3, :city3, :phone3)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/helpers/headhunters_helper.rb
module HeadhuntersHelper
end

app/views/headhunters/_form.html.erb
<%= form_for @headhunter, html: { multipart: true } do |f| %>
  <% if @headhunter.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@headhunter.errors.count, "error") %> prohibited this headhunter from being saved:</h2>

      <ul>
      <% @headhunter.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :CompanyName %>
    <%= f.text_field :CompanyName, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyDescription %>
    <%= f.text_area :CompanyDescription, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyEmail %>
    <%= f.text_field :CompanyEmail, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyWebsite %>
    <%= f.text_field :CompanyWebsite, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyLinkedin %>
    <%= f.text_field :CompanyLinkedin, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyFacebook %>
    <%= f.text_field :CompanyFacebook, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyTwitter %>
    <%= f.text_field :CompanyTwitter, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="checkbox">
    <%= f.label :CompanyUndergrad %>
    <%= f.check_box :CompanyUndergrad, class: "checkbox" %>
  </div>
  <div class="checkbox">
    <%= f.label :CompanyPreMBA %>
    <%= f.check_box :CompanyPreMBA, class: "checkbox" %>
  </div>
  <div class="checkbox">
    <%= f.label :CompanyPostMBA %>
    <%= f.check_box :CompanyPostMBA, class: "checkbox" %>
  </div>
  <div class="checkbox">
    <%= f.label :CompanyExecutive %>
    <%= f.check_box :CompanyExecutive, class: "checkbox" %>
  </div>
  <br />
  <div class="checkbox">
    <%= f.label :mega %>
    <%= f.check_box :mega, class: "checkbox" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyCandidateArea %>
    <%= f.text_area :CompanyCandidateArea, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :CompanyJobs %>
    <%= f.text_area :CompanyJobs, class: "form-control" %>
  </div>
  <div class="row">
    <div class="col-xs-4">
      <div class="form-group">
        <%= f.label :street1 %>
        <%= f.text_field :street1, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city1 %>
        <%= f.text_field :city1, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone1 %>
        <%= f.text_field :phone1, class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="form-group">
        <%= f.label :street2 %>
        <%= f.text_field :street2, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city2 %>
        <%= f.text_field :city2, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone2 %>
        <%= f.text_field :phone2, class: "form-control" %>
      </div>
    </div>
    <div class="col-xs-4">
      <div class="form-group">
        <%= f.label :street3 %>
        <%= f.text_field :street3, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city3 %>
        <%= f.text_field :city3, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :phone3 %>
        <%= f.text_field :phone3, class: "form-control" %>
      </div>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/headhunters/edit.html.erb
<div class="container">
	<h1>Edit Headhunter</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @headhunter %> |
	<%= link_to 'Back', headhunters_path %>
</div>

app/views/headhunters/index.html.erb
<div class="container">
  <% if current_user.try(:admin?) %>
    <%= link_to new_headhunter_path do %>
      <span class="fa fa-plus-circle"></span>
      New Headhunter
    <% end %>
  <% end %>
  <div class="row">
    <div class="col-md-3">
      <div class="panel panel-default" style="margin-top: 5px;">
        <div class="panel-body">
          
          <form action='' method="get">
            <h5><strong>CLIENT TYPES</strong></h5>
            <div class="small">
              <%= check_box_tag :isMega %>
              <%= label_tag :isMega, "Mega Funds", class: 'label_filter' %>
            </div>
            <h5><strong>LEVEL</strong></h5>
            <div class="small">
              <%= check_box_tag :Undergrad %>
              <%= label_tag :Undergrad, "Undergrad", class: 'label_filter' %>
            </div>
            <div class="small">
              <%= check_box_tag :PreMBA %>
              <%= label_tag :PreMBA, "PreMBA", class: 'label_filter' %>
           </div>
            <div class="small">
              <%= check_box_tag :PostMBA %>
              <%= label_tag :PostMBA, "PostMBA", class: 'label_filter' %>
            </div>
            <div class="small">
              <%= check_box_tag :Executive %>
              <%= label_tag :Executive, "Executive", class: 'label_filter' %>
            </div>
            <h5><strong>OTHER</strong></h5>
            <div class="small">
              <%= check_box_tag :hasJobs %>
              <%= label_tag :hasJobs, "Job Listings", class: 'label_filter' %>
            </div>
            <%= submit_tag 'Filter', name: nil, class: "btn btn-primary" %>
          </form>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div id="headhunters" class="transitions-enabled">
        <% @headhunters.each do |headhunter| %>
          <div class="box panel panel-default">
            <%= link_to image_tag(headhunter.image.url(:medium)), headhunter %>
            <div class="panel-body">
              <p><strong><small><%= link_to headhunter.CompanyName, headhunter,  :class => "link-dark-gray" %></small></strong></p>
              <p style="line-height: 0"><small><%= link_to headhunter.CompanyWebsite, "http://#{headhunter.CompanyWebsite}", :class => "link-dark-gray" %></small> </p>         
              <% if current_user.try(:admin?) %>
                <div class="actions">
                  <%= link_to edit_headhunter_path(headhunter) do %>
                    <span class="fa fa-edit"></span>
                    Edit
                  <% end %>
                  <%= link_to headhunter, method: :delete, data: { confirm: 'Are you sure?' } do %>
                    <span class="fa fa-trash"></span>
                    Delete
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        <% end %>        
      </div>
      <div class="center">
        <%= will_paginate @pages, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  </div>
</div>

app/views/headhunters/new.html.erb
<div class="container">
	<h1>New Headhunter</h1>

	<%= render 'form' %>

	<%= link_to 'Back', headhunters_path %>
</div>

app/views/headhunters/show.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<!-- MODAL -->
	<div class="modal fade" id="recruiterModal" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
					<h4 class="modal-title" id="recruiterName" />
				</div>
				<div class="modal-body">
					<p id="recruiterDesc" />
				</div>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12 link-dark-gray">
			<%= link_to 'Back', headhunters_path, :class => "link-dark-gray" %>
			<% if current_user.try(:admin?) %>
				 | 
				<%= link_to edit_headhunter_path(@headhunter) do %>
					<span class="fa fa-edit"></span>
					Edit
				<% end %>
			<% end %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-default">
				<div class="panel-body">
					<div class="row">
						<div class="col-md-2">
							<%= image_tag @headhunter.image.url(:medium), class: "img-thumbnail" %>
						</div>
						<div class="col-md-10">
							<h2><%= @headhunter.CompanyName %></h2>
							<small><%= @headhunter.CompanyDescription %></small>
						</div>
					</div>
				</div>
				<div class="panel-body right" style="background-color: #5a5a5a;">
					<%= link_to @headhunter.CompanyWebsite, "http://#{@headhunter.CompanyWebsite}", class: "link-gray" %>
					<% if @headhunter.CompanyEmail == "None" %>

					<% else %>
						&nbsp;
						<%= mail_to @headhunter.CompanyEmail do %>
							<i class="fa fa-envelope fa-lg link-gray"></i>
						<% end %>
					<% end %>
					<% if @headhunter.CompanyLinkedin == "None" %>

					<% else %>
						&nbsp;
						<%= link_to "http://#{@headhunter.CompanyLinkedin}" do %>
							<i class="fa fa-linkedin fa-lg link-gray"></i>
						<% end %>
					<% end %>
					<% if @headhunter.CompanyFacebook == "None" %>

					<% else %>
						&nbsp;
						<%= link_to "http://#{@headhunter.CompanyFacebook}" do %>
							<i class="fa fa-facebook fa-lg link-gray"></i>
						<% end %>
					<% end %>
					<% if @headhunter.CompanyTwitter == "None" %>

					<% else %>
						&nbsp;
						<%= link_to "http://#{@headhunter.CompanyTwitter}" do %>
							<i class="fa fa-twitter fa-lg link-gray"></i>
						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-md-3">
			<div class="row">
				<div class="col-md-12">
					<div class="panel panel-default">
						<div class="panel-body">
							<!--<h5><strong>CLIENT TYPES</strong></h5>
							<% if @headhunter.mega %><small><p>Mega Funds</p></small><% end %>
							<br />-->
							<h5><strong>LEVEL</strong></h5>
							<p><small>
							<% if @headhunter.CompanyUndergrad %>Undergrad<br /><% end %>
							<% if @headhunter.CompanyPreMBA %>PreMBA<br /><% end %>
							<% if @headhunter.CompanyPostMBA %>PostMBA<br /><% end %>
							<% if @headhunter.CompanyExecutive %>Executive<% end %>
							</small></p>
						</div>
					</div>
				</div>
			</div>
			<!-- CANDIDATE AREA -->
			<% if @headhunter.CompanyCandidateArea == "None" %>

			<% else %>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<h5><strong>CANDIDATE AREA</strong></h5>
								<small><%= raw @headhunter.CompanyCandidateArea %></small>
							</div>
						</div>
					</div>
				</div>
			<% end %>
			<!-- JOBS AREA -->
			<% if @headhunter.CompanyJobs == "None" %>

			<% else %>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<h5><strong>CURRENT SEARCHES</strong></h5>
								<small><%= raw @headhunter.CompanyJobs %></small>
							</div>
						</div>
					</div>
				</div>
			<% end %>
			<!-- OFFICE AREA -->
			<% if @headhunter.street1 == "None" %>

			<% else %>
				<div class="row">
					<div class="col-md-12">
						<div class="panel panel-default">
							<div class="panel-body">
								<h5><strong>OFFICES</strong></h5>
									<small>
										<%= @headhunter.street1 %><br />
										<%= @headhunter.city1 %><br />
										<%= @headhunter.phone1 %><br />
										<% if @headhunter.street2 == "None" %>

										<% else %>
											<br />
											<%= @headhunter.street2 %><br />
											<%= @headhunter.city2 %><br />
											<%= @headhunter.phone2 %><br />
										<% end %>
										<% if @headhunter.street3 == "None" %>

										<% else %>
											<br />
											<%= @headhunter.street3 %><br />
											<%= @headhunter.city3 %><br />
											<%= @headhunter.phone3 %><br />
										<% end %>
									</small>
							</div>
						</div>
					</div>
				</div>
			<% end %>
		</div>
		<!-- TEAM AREA -->
		<div class="col-md-9">
			<div class="panel panel-default">
				<div class="panel-body">
					<h4>Team</h4>
					<hr style="margin-top: -5px;">
					<div id="recruiters" class="transitions-enabled">
    				<% @recruiters.each do |recruiter| %>
    					<div class="box-recruiters center" style="margin-top: 10px;">	          	
								<%= link_to( image_tag(recruiter.image.url(:medium), :class => "img-circle"), "#recruiterModal", :class => "recruiterBio", :data => {:toggle => "modal", :description => "#{recruiter.description}", :name => "#{recruiter.name}"}) %>	
	          		<p style="line-height: 1.0; margin-top: 5px;"><%= recruiter.name %></p>
	          		<p style="line-height: 0;"><small><%= recruiter.title %></small></p>
	          		<% if recruiter.email == "None" %>

								<% else %>
		          		<%= mail_to recruiter.email do %>
										<i class="fa fa-envelope fa-lg link-dark-gray"></i>
									<% end %>
								<% end %>
								<% if recruiter.linkedin == "None" %>

								<% else %>
									<%= link_to "http://#{recruiter.linkedin}" do %>
										<i class="fa fa-linkedin fa-lg link-dark-gray"></i>
									<% end %>
								<% end %>
	      			</div>
    				<% end %>
    			</div>
    			<div class="center">
    				<%= will_paginate @recruiters, renderer: BootstrapPagination::Rails %>
  				</div>
				</div>
			</div>
			<%= render 'layouts/data' %>
		</div>
	</div>
</div>