config/routes.rb
Refout::Application.routes.draw do
  resources :tips do
    member do
      put "addupvote", to: "tips#addupvote"
    end
  end

  resources :groups

  resources :offices

  resources :banks do
    get :offices, :on => :member
    get :groups, :on => :member
    get :schools, :on => :member
  end

  resources :recruiters

  resources :headhunters

  scope '/resources' do
    resources :tips
    get "what-to-read" => "pages#resources/what-to-read"
  end

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "resources" => "pages#resources"
  get "legal" => "pages#legal"
  

end

app/models/office.rb
class Office < ActiveRecord::Base
	belongs_to :bank

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing_recruiter.jpg"
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]
  before_filter :verify_is_admin, only: [:new, :edit, :update, :destroy, :index, :show]


  def index
    Office.joins(:office, :bank).where("office.bank_id = bank.id")
    @offices = Office.all.order("updated_at DESC")
  end

  def show
    Office.joins(:office, :bank).where("office.bank_id = bank.id")
    @office = Office.find(params[:id])
    @bank = Bank.find(@office.bank_id)
  end

  def new
    @office = Office.new
  end

  def edit
  end

  def create
    @office = Office.new(office_params)

    if @office.save
      redirect_to @office, notice: 'Office was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @office.update(office_params)
      redirect_to @office, notice: 'Office was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @office.destroy
    redirect_to officers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :description, :bank_id, :street, :city, :phone, :image)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.erb
<%= form_for @office, html: { multipart: true }  do |f| %>
  <% if @office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@office.errors.count, "error") %> prohibited this office from being saved:</h2>

      <ul>
      <% @office.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :bank_id %><br>
    <%= f.collection_select :bank_id, Bank.all.order(:shortname), :id, :shortname, {:include_blank => "Select Bank"}, {class: "form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :street %><br>
    <%= f.text_field :street, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :city %><br>
    <%= f.text_field :city, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/offices/edit.html.erb
<div class="container">
<h1>Editing office</h1>

<%= render 'form' %>

<%= link_to 'Show', @office %> |
<%= link_to 'Back', offices_path %>
</div>

app/views/offices/index.html.erb
<div class="container">
<% if current_user.try(:admin?) %>
  <%= link_to new_office_path do %>
    <span class="fa fa-plus-circle"></span>
    New Office
  <% end %>
<% end %>
<h1>List of Offices</h1>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Bank</th>
        <th>Last Updated</th>
      </tr>
    </thead>

    <tbody>
      <% @offices.each do |office| %>
        <tr>
          <td><%= link_to office.name, office %></td>
          <td><%= link_to office.bank.try(:shortname).blank? ? 'N/A' : office.bank.shortname, office.bank %></td>
          <td><%= office.updated_at.strftime("%m/%d/%Y") %></td>       
          <td>
            <%= link_to edit_office_path(office) do %>
              <span class="fa fa-edit"></span>
              Edit
            <% end %>
          </td>
          <td>
            <%= link_to office, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="fa fa-trash"></span>
              Delete
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/offices/new.html.erb
<div class="container">
	<h1>New office</h1>

	<%= render 'form' %>

	<%= link_to 'Back', offices_path %>
</div>

app/views/offices/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <%= render 'layouts/bank/header' %>
  <div class="row">
    <div class="col-md-3">
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <%= render 'layouts/bank/sidenav' %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-9">
      <div class="row">
        <div class="col-md-12">
          <div class="panel panel-default">
            <div class="panel-body">
              <h4><%= @office.name %></h4>
              <hr style="margin-top: -5px;">
              <small>
                <%= @office.street %><br />
                <%= @office.city %><br />
                <%= @office.phone %><br />
              </small>
              <br />
              <p><%= @office.description %></p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">
          <%= render 'layouts/bank/office/' + @bank.shortname + '/' + @office.name.downcase.gsub(/\s+/, "") %>
          <%= render 'layouts/data' %>
        </div>
      </div>
    </div>
  </div>
</div>