config/routes.rb
Refout::Application.routes.draw do
  resources :tips do
    member do
      put "addupvote", to: "tips#addupvote"
    end
  end

  resources :groups

  resources :offices

  resources :banks do
    get :offices, :on => :member
    get :groups, :on => :member
    get :schools, :on => :member
  end

  resources :recruiters

  resources :headhunters

  scope '/resources' do
    resources :tips
    get "what-to-read" => "pages#resources/what-to-read"
  end

  devise_for :users
  root "pages#home"
  get "about" => "pages#about"
  get "contact" => "pages#contact"
  get "resources" => "pages#resources"
  get "legal" => "pages#legal"
  

end

app/models/bank.rb
class Bank < ActiveRecord::Base
	has_many :offices
	has_many :groups

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/group.rb
class Group < ActiveRecord::Base
	belongs_to :bank

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing_recruiter.jpg"
end

app/models/headhunter.rb
class Headhunter < ActiveRecord::Base
	has_many :recruiters

	scope :isMega, -> {where(:mega => true)}
	scope :Undergrad, -> {where(:CompanyUndergrad => true)}
	scope :PreMBA, -> {where(:CompanyPreMBA => true)}
	scope :PostMBA, -> {where(:CompanyPostMBA => true)}
	scope :Executive, -> {where(:CompanyExecutive => true)}
	scope :hasJobs, -> {where("\"CompanyJobs\" != ?", "None")}

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/models/office.rb
class Office < ActiveRecord::Base
	belongs_to :bank

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing_recruiter.jpg"
end

app/models/recruiter.rb
class Recruiter < ActiveRecord::Base
	belongs_to :headhunter

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "missing_recruiter.jpg"
end

app/models/tip.rb
class Tip < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/banks_controller.rb
class BanksController < ApplicationController
  before_action :set_bank, only: [:show, :edit, :update, :destroy]


  def index
    @banks = apply_scopes(Bank.all.order(:name).paginate(:page => params[:page], :per_page => 24))
  end

  def show
  end

  def new
    @bank = Bank.new
  end

  def edit
  end

  def create
    @bank = Bank.new(bank_params)

    if @bank.save
      redirect_to @bank, notice: 'Bank was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @bank.update(bank_params)
      redirect_to @bank, notice: 'Bank was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @bank.destroy
    redirect_to banks_url
  end

  def offices
    @bank = Bank.find(params[:id])
    @offices = @bank.offices  
  end

  def groups
    @bank = Bank.find(params[:id])
    @groups = @bank.groups  
  end

  def schools
    @bank = Bank.find(params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bank
      @bank = Bank.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bank_params
      params.require(:bank).permit(:name, :shortname, :image, :description, :website, :email, :facebook, :twitter, :linkedin, :youtube, :size, :geography, :industries, :products, :founded, :internship, :diversity, :underclass, :charity, :revenue, :stock, :employees, :ceo, :headquarters)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_filter :verify_is_admin, only: [:new, :edit, :update, :destroy, :index, :show]


  def index
    Group.joins(:group, :bank).where("group.bank_id = bank.id")
    @groups = Group.all.order("updated_at DESC")
  end

  def show
    Group.joins(:group, :bank).where("group.bank_id = bank.id")
    @group = Group.find(params[:id])
    @bank = Bank.find(@group.bank_id)
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)

    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @group.update(group_params)
      redirect_to @group, notice: 'Group was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :description, :bank_id, :image)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]
  before_filter :verify_is_admin, only: [:new, :edit, :update, :destroy, :index, :show]


  def index
    Office.joins(:office, :bank).where("office.bank_id = bank.id")
    @offices = Office.all.order("updated_at DESC")
  end

  def show
    Office.joins(:office, :bank).where("office.bank_id = bank.id")
    @office = Office.find(params[:id])
    @bank = Bank.find(@office.bank_id)
  end

  def new
    @office = Office.new
  end

  def edit
  end

  def create
    @office = Office.new(office_params)

    if @office.save
      redirect_to @office, notice: 'Office was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @office.update(office_params)
      redirect_to @office, notice: 'Office was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @office.destroy
    redirect_to officers_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :description, :bank_id, :street, :city, :phone, :image)
    end

    def verify_is_admin
      (current_user.nil?) ? redirect_to(root_path) : (redirect_to(root_path) unless current_user.admin?)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end


end

app/controllers/tips_controller.rb
class TipsController < ApplicationController
  before_action :set_tip, only: [:show, :edit, :update, :destroy]

  def index
    @tips = Tip.all.order("upvote DESC")
  end

  def show
  end

  def new
    @tip = Tip.new
  end

  def edit
  end

  def create
    @tip = Tip.new(tip_params)
    if @tip.save
      redirect_to @tip, notice: 'Tip was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @tip.update(tip_params)
      redirect_to @tip, notice: 'Tip was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @tip.destroy
    redirect_to tips_url
  end

  def addupvote
    @tip = Tip.find(params[:id])
    @tip.upvote += 1
    @tip.save!
    redirect_to request.referrer
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tip
      @tip = Tip.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tip_params
      params.require(:tip).permit(:description, :title, :upvote)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/banks_helper.rb
module BanksHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/headhunters_helper.rb
module HeadhuntersHelper
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recruiters_helper.rb
module RecruitersHelper
end

app/helpers/tips_helper.rb
module TipsHelper
end

app/views/layouts/_bankheader.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1 link-dark-gray">
    <%= link_to 'Back', banks_path, :class => "link-dark-gray" %>
    <% if current_user.try(:admin?) %>
       | 
      <%= link_to edit_bank_path(@bank) do %>
        <span class="fa fa-edit"></span>
        Edit
      <% end %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <div class="panel panel-default">
      <div class="panel-body">
        <div class="row">
          <div class="col-md-2">
            <%= image_tag @bank.image.url(:medium), class: "img-thumbnail" %>
          </div>
          <div class="col-md-10">
            <h2><%= @bank.name %></h2>
            <small><%= @bank.description %></small>
          </div>
        </div>
      </div>
      <div class="panel-body right" style="background-color: #5a5a5a;">
        <%= link_to @bank.website, "http://#{@bank.website}", class: "link-gray" %>
        <% if @bank.email == "None" %>

        <% else %>
          &nbsp;
          <%= mail_to @bank.email do %>
            <i class="fa fa-envelope fa-lg link-gray"></i>
          <% end %>
        <% end %>
        <% if @bank.linkedin == "None" %>

        <% else %>
          &nbsp;
          <%= link_to "http://#{@bank.linkedin}" do %>
            <i class="fa fa-linkedin fa-lg link-gray"></i>
          <% end %>
        <% end %>
        <% if @bank.facebook == "None" %>

        <% else %>
          &nbsp;
          <%= link_to "http://#{@bank.facebook}" do %>
            <i class="fa fa-facebook fa-lg link-gray"></i>
          <% end %>
        <% end %>
        <% if @bank.twitter == "None" %>

        <% else %>
          &nbsp;
          <%= link_to "http://#{@bank.twitter}" do %>
            <i class="fa fa-twitter fa-lg link-gray"></i>
          <% end %>
        <% end %>
        <% if @bank.youtube == "None" %>

        <% else %>
          &nbsp;
          <%= link_to "http://#{@bank.youtube}" do %>
            <i class="fa fa-youtube fa-lg link-gray"></i>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_banksidenav.html.erb
<h5><strong>PROFESSIONALS</strong></h5>
  <small><p>
    Schools<br />
    Exit Ops
  </p></small>
<h5><strong>STRUCTURE</strong></h5>
  <small><p>
    <%= link_to "Offices", offices_bank_path(@bank) %><br />
    Groups
  </p></small>
<h5><strong>RECRUITING</strong></h5>
  <small><p>
    Full-Time<br />
    Internship<br />
    Diversity<br />
    Underclassmen
  </p></small>
<h5><strong>OTHER</strong></h5>
  <small><p>
    Charity Work<br />
    Recent News
  </p></small>

app/views/layouts/_data.html.erb
<div class="small" style="color: #95a5a6;">Ref Out is not responsible for accuracy of the data above. Data points are meant to be directional, not 100% complete.</div>

app/views/layouts/_footer.html.erb
<div id="footer"> 
	<div class="container" style="margin-top: 15px;">
		<strong><a id="submitnew" data-toggle="popover">+ ADD DATA</a></strong>

		<div id="popover_content_wrapper" style="display: none">
  		<div>Please send us an email at <a href="mailto:hello@refout.com">hello@refout.com</a></div>
		</div>

		 &nbsp; &nbsp;
		<%= link_to "BLOG", "http://refout.tumblr.com" %> &nbsp; &nbsp;
		<%= link_to "ABOUT", about_path %> &nbsp; &nbsp;
		<%= link_to "CONTACT", contact_path %> &nbsp; &nbsp;
		<div style="float:right">
			<%= link_to "https://www.facebook.com/pages/Ref-Out/277440142433174" do %>
				<i class="fa fa-facebook fa-lg link-social" style="font-size: 24px;"></i>
			<% end %>
			&nbsp; &nbsp;
			<%= link_to "http://www.twitter.com/refout" do %>
				<i class="fa fa-twitter fa-lg link-social" style="font-size: 24px;"></i>
			<% end %>
			&nbsp; &nbsp;
			&copy; 2014 WATER COOLER LABS
			&nbsp; &nbsp;
			<%= link_to "LEGAL", legal_path %>

		</div>
	</div>
</div>

<script>

$('a#submitnew').click(function() {
  $('a#submitnew').popover({
    html: true,
    trigger: 'manual',
    placement: 'top',
    content: function() {
    	return $('#popover_content_wrapper').html();
    },
    title: 'Submit New Data'
  });
  $('a#submitnew').popover("show");
});

$('body').on('click', function (e) {
  $('[data-toggle="popover"]').each(function () {
  	//the 'is' for buttons that trigger popups
  	//the 'has' for icons within a button that triggers a popup
    if (!$(this).is(e.target) && $(this).has(e.target).length === 0 && $('.popover').has(e.target).length === 0) {
            $(this).popover('hide');
    }
  });
});

</script>

app/views/layouts/_ga.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48722911-2', 'peaceful-forest-9000.herokuapp.com');
  ga('send', 'pageview');

</script>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to image_tag("logo-250px.png", :size => "80x50", :style => "margin-top: 0px;"), root_path %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" style="font-weight: 300;">
        <li class="disabled"><%= link_to "BANKS", "#" %></li>
        <li><%= link_to "HEADHUNTERS", headhunters_path %></li>
        <li><%= link_to "RESOURCES", resources_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right" style="font-weight: 300;">
        <% if user_signed_in? %>
          <li><%= link_to "SETTINGS", edit_user_registration_path %></li>
          <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/_sidenav.html.erb
<ul class="nav nav_pages" style="background-color: white;">
	<li><%= link_to "Blog", "http://www.refout.tumblr.com", :class => "link-dark-gray" %></li>
	<li><%= link_to "About", about_path, :class => "link-dark-gray" %></li>
	<li><%= link_to "Contact", contact_path, :class => "link-dark-gray" %></li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Ref Out</title>
	  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
	  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	  <%= csrf_meta_tags %>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	  <%= stylesheet_link_tag 'application', 'http://fonts.googleapis.com/css?family=Open+Sans:400,700,300,600' %>

	  <link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png">
		<link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png">
		<link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png">
		<link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png">
		<link rel="apple-touch-icon" sizes="60x60" href="/apple-touch-icon-60x60.png">
		<link rel="apple-touch-icon" sizes="120x120" href="/apple-touch-icon-120x120.png">
		<link rel="apple-touch-icon" sizes="76x76" href="/apple-touch-icon-76x76.png">
		<link rel="apple-touch-icon" sizes="152x152" href="/apple-touch-icon-152x152.png">
		<link rel="icon" type="image/png" href="/favicon-196x196.png" sizes="196x196">
		<link rel="icon" type="image/png" href="/favicon-160x160.png" sizes="160x160">
		<link rel="icon" type="image/png" href="/favicon-96x96.png" sizes="96x96">
		<link rel="icon" type="image/png" href="/favicon-16x16.png" sizes="16x16">
		<link rel="icon" type="image/png" href="/favicon-32x32.png" sizes="32x32">
		<meta name="msapplication-TileColor" content="#71c6c1">
		<meta name="msapplication-TileImage" content="/mstile-144x144.png">
	  
	</head>
	<body>
		<% if current_page?(root_path) %>

		<% else %>
			<%= render 'layouts/header' %>
		<% end %>
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end %>
		<%= yield %>
		<div id="push"></div>

		<%= render 'layouts/footer' %>

		<%= render 'layouts/ga' if Rails.env.production? %>

	</body>
</html>

app/views/pages/resources/what-to-read.html.erb
<div class="jumbotron what_to_read_jumbo">
  <div class="container">
    <h1><b>What to Read Around the Web</b></h1>
    <h4>Resources from industry news to banking life</h4>
    <hr width="20%" style="margin-top: 15px; margin-bottom: 15px;">
    <small><i>curated by</i></small>
    <br />
    <%= image_tag "resources/refout_team_icon.jpg", :size => "50x50", :class => "img-circle", :style => "margin-top: 15px;" %>
    <br />
    <small>The Ref Out Team</small>
  </div>
</div>
<div class="container">
  <div class="panel panel-default">
    <div class="panel-body">
      <h4>Industry News</h4>
      <hr style="margin-top: -5px;">
      <div>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/wsj_logo.jpg", :size => "50x50"), "http://www.wsj.com" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Wall Street Journal", "http://www.wsj.com" %>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/bloomberg_logo.jpg", :size => "50x50"), "http://www.bloomberg.com" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Bloomberg", "http://www.bloomberg.com" %>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/dealbook_logo.jpg", :size => "50x50"), "http://www.dealbook.com" %>
              </div>
              <div class="col-md-11">
                <%= link_to "DealBook", "http://www.dealbook.com" %>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/cnbc_logo.jpg", :size => "50x50"), "http://www.cnbc.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "CNBC", "http://www.cnbc.com/" %>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/economist_logo.jpg", :size => "50x50"), "http://www.economist.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "The Economist", "http://www.economist.com/" %>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <h4>Newsletters</h4>
      <hr style="margin-top: -5px;">
      <div>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/termsheet_logo.jpg", :size => "50x50"), "http://fortune.com/tag/term-sheet/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Term Sheet", "http://fortune.com/tag/term-sheet/" %> by Dan Primack is a daily email digest recapping the day's private equity and venture capital deals and other industry news. It's a must-read for those in the financial industry.
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/pehub_logo.jpg", :size => "50x50"), "https://www.pehub.com/pewire-signup/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "peHUB Wire", "https://www.pehub.com/pewire-signup/" %> is the daily must-read email for more than 60,000 people, providing breaking news and unique, insightful commentary on the private equity and venture capital industry.
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/quartz_logo.jpg", :size => "50x50"), "http://qz.com/daily-brief" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Quartz Daily Brief", "http://qz.com/daily-brief" %> is a cleverly written and edited newsletter from The Atlantic that has a good mix of news, fun, and thoughtful items.
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/dwc_logo.jpg", :size => "50x50"), "https://www.the-dwc.co" %>
              </div>
              <div class="col-md-11">
                <%= link_to "The Daily Water Cooler", "https://www.the-dwc.co" %> is an email newsletter with news and humor delivered every weekday morning to make sure you're never left behind in a conversation. Covers highlights in business, politics sports, culture, and more.
              </div>
            </div>
          </li>
        </ul>
      </div>
      <h4>Community and Culture</h4>
      <hr style="margin-top: -5px;">
      <div>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/wso_logo.jpg", :size => "50x50"), "http://www.wallstreetoasis.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Wall Street Oasis", "http://www.wallstreetoasis.com/" %> is one of the largest and most entertaining finance communities online.
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/dealbreaker_logo.jpg", :size => "50x50"), "http://dealbreaker.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Dealbreaker", "http://dealbreaker.com/" %> covers the personalities and culture that shape the financial industry, offering original commentary, news and entertainment. 
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/lso_logo.jpg", :size => "50x50"), "http://www.leveragedsellout.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "The Leveraged Sell-Out", "http://www.leveragedsellout.com/" %>
              </div>
            </div>
          </li>
        </ul>
      </div>
      <h4>Recruiting and Interviewing</h4>
      <hr style="margin-top: -5px;">
      <div>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/mi_logo.jpg", :size => "50x50"), "http://www.mergersandinquisitions.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Mergers & Inquisitions", "http://www.mergersandinquisitions.com/" %>
              </div>
            </div>
          </li>
          <li class="list-group-item">
            <div class="row">
              <div class="col-md-1">
                <%= link_to image_tag("resources/resource_logo/vault_logo.jpg", :size => "50x50"), "http://www.vault.com/" %>
              </div>
              <div class="col-md-11">
                <%= link_to "Vault", "http://www.vault.com/" %>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>